//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.App.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Accounting.App.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1486146612_propertyagent002_79450 {
            get {
                object obj = ResourceManager.GetObject("_1486146612_propertyagent002_79450", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon _1491253669_6document_report_82892 {
            get {
                object obj = ResourceManager.GetObject("_1491253669_6document_report_82892", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1491253669_6document_report_828921 {
            get {
                object obj = ResourceManager.GetObject("_1491253669_6document_report_828921", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon _1492533007_money_magnet_83249 {
            get {
                object obj = ResourceManager.GetObject("_1492533007_money_magnet_83249", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1492533007_money_magnet_832491 {
            get {
                object obj = ResourceManager.GetObject("_1492533007_money_magnet_832491", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon _3586357_audio_record_sound_speaker_107952 {
            get {
                object obj = ResourceManager.GetObject("_3586357_audio_record_sound_speaker_107952", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3586357_audio_record_sound_speaker_1079521 {
            get {
                object obj = ResourceManager.GetObject("_3586357_audio_record_sound_speaker_1079521", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon _3741735_bussiness_ecommerce_marketplace_onlinestore_sotore_store_108894 {
            get {
                object obj = ResourceManager.GetObject("_3741735_bussiness_ecommerce_marketplace_onlinestore_sotore_store_108894", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3741735_bussiness_ecommerce_marketplace_onlinestore_sotore_store_1088941 {
            get {
                object obj = ResourceManager.GetObject("_3741735_bussiness_ecommerce_marketplace_onlinestore_sotore_store_1088941", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon _3741759_artboard_bussiness_ecommerce_marketplace_onlinestore_store_trolly_108893 {
            get {
                object obj = ResourceManager.GetObject("_3741759_artboard_bussiness_ecommerce_marketplace_onlinestore_store_trolly_108893" +
                        "", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3741759_artboard_bussiness_ecommerce_marketplace_onlinestore_store_trolly_1088931 {
            get {
                object obj = ResourceManager.GetObject("_3741759_artboard_bussiness_ecommerce_marketplace_onlinestore_store_trolly_108893" +
                        "1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3925398_budget_money_stocks_icon_111548 {
            get {
                object obj = ResourceManager.GetObject("_3925398_budget_money_stocks_icon_111548", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3925398_budget_money_stocks_icon_111548_1_ {
            get {
                object obj = ResourceManager.GetObject("_3925398_budget_money_stocks_icon_111548_1_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4124799_finance_report_graph_analysis_graph_report_sale_report_stock_report_113890 {
            get {
                object obj = ResourceManager.GetObject("_4124799_finance_report_graph_analysis_graph_report_sale_report_stock_report_1138" +
                        "90", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4124799_finance_report_graph_analysis_graph_report_sale_report_stock_report_113890_1_ {
            get {
                object obj = ResourceManager.GetObject("_4124799_finance_report_graph_analysis_graph_report_sale_report_stock_report_1138" +
                        "90_1_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon _4124827_ad_advertisement_marketing_mobile_mobile_advertising_113898 {
            get {
                object obj = ResourceManager.GetObject("_4124827_ad_advertisement_marketing_mobile_mobile_advertising_113898", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4124827_ad_advertisement_marketing_mobile_mobile_advertising_113898__1_ {
            get {
                object obj = ResourceManager.GetObject("_4124827_ad_advertisement_marketing_mobile_mobile_advertising_113898__1_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4124827_ad_advertisement_marketing_mobile_mobile_advertising_1138981 {
            get {
                object obj = ResourceManager.GetObject("_4124827_ad_advertisement_marketing_mobile_mobile_advertising_1138981", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4124841_finance_report_graph_analysis_graph_report_sale_report_stock_report_114127 {
            get {
                object obj = ResourceManager.GetObject("_4124841_finance_report_graph_analysis_graph_report_sale_report_stock_report_1141" +
                        "27", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4124841_finance_report_graph_analysis_graph_report_sale_report_stock_report_114127_1_ {
            get {
                object obj = ResourceManager.GetObject("_4124841_finance_report_graph_analysis_graph_report_sale_report_stock_report_1141" +
                        "27_1_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4213589_calculate_calculator_doodle_education_line_school_vector_115495 {
            get {
                object obj = ResourceManager.GetObject("_4213589_calculate_calculator_doodle_education_line_school_vector_115495", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon _4544837_business_comerce_delivery_guarante_shop_121437 {
            get {
                object obj = ResourceManager.GetObject("_4544837_business_comerce_delivery_guarante_shop_121437", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4544837_business_comerce_delivery_guarante_shop_1214371 {
            get {
                object obj = ResourceManager.GetObject("_4544837_business_comerce_delivery_guarante_shop_1214371", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon _4544845_business_comerce_delivery_list_shop_121445 {
            get {
                object obj = ResourceManager.GetObject("_4544845_business_comerce_delivery_list_shop_121445", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4544845_business_comerce_delivery_list_shop_1214451 {
            get {
                object obj = ResourceManager.GetObject("_4544845_business_comerce_delivery_list_shop_1214451", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _person_add_89833 {
            get {
                object obj = ResourceManager.GetObject("_person_add_89833", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon account_profile_user_ecommerce_icon_224942 {
            get {
                object obj = ResourceManager.GetObject("account_profile_user_ecommerce_icon_224942", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap account_profile_user_ecommerce_icon_2249421 {
            get {
                object obj = ResourceManager.GetObject("account_profile_user_ecommerce_icon_2249421", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap accounting_calculator_clipboard_notes_icon_188648 {
            get {
                object obj = ResourceManager.GetObject("accounting_calculator_clipboard_notes_icon_188648", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon accounting_icon_152112 {
            get {
                object obj = ResourceManager.GetObject("accounting_icon_152112", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap analytics_report_analysis_document_data_study_icon_143867 {
            get {
                object obj = ResourceManager.GetObject("analytics_report_analysis_document_data_study_icon_143867", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap analytics_report_analysis_document_data_study_icon_143867_1_ {
            get {
                object obj = ResourceManager.GetObject("analytics_report_analysis_document_data_study_icon_143867_1_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon attraction_icon_180765 {
            get {
                object obj = ResourceManager.GetObject("attraction_icon_180765", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap attraction_icon_1807651 {
            get {
                object obj = ResourceManager.GetObject("attraction_icon_1807651", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon attraction_star_favourite_icon_180184 {
            get {
                object obj = ResourceManager.GetObject("attraction_star_favourite_icon_180184", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap attraction_star_favourite_icon_1801841 {
            get {
                object obj = ResourceManager.GetObject("attraction_star_favourite_icon_1801841", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon bag_buy_cart_ecommerce_shop_shopping_store_icon_123227 {
            get {
                object obj = ResourceManager.GetObject("bag_buy_cart_ecommerce_shop_shopping_store_icon_123227", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bag_buy_cart_ecommerce_shop_shopping_store_icon_1232271 {
            get {
                object obj = ResourceManager.GetObject("bag_buy_cart_ecommerce_shop_shopping_store_icon_1232271", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon businessman_avatar_with_question_mark_icon_icons_com_68324 {
            get {
                object obj = ResourceManager.GetObject("businessman_avatar_with_question_mark_icon_icons_com_68324", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap businessman_avatar_with_question_mark_icon_icons_com_683241 {
            get {
                object obj = ResourceManager.GetObject("businessman_avatar_with_question_mark_icon_icons_com_683241", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap caculator_and_book_icon_icons_com_70277 {
            get {
                object obj = ResourceManager.GetObject("caculator_and_book_icon_icons_com_70277", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap calculation_math_computation_arithmetic_figuring_icon_262941 {
            get {
                object obj = ResourceManager.GetObject("calculation_math_computation_arithmetic_figuring_icon_262941", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap calendar_and_briefcase_icon_icons_com_70274 {
            get {
                object obj = ResourceManager.GetObject("calendar_and_briefcase_icon_icons_com_70274", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap calendar_and_envelope_icon_icons_com_70272 {
            get {
                object obj = ResourceManager.GetObject("calendar_and_envelope_icon_icons_com_70272", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap calendar_and_user_icon_icons_com_70271 {
            get {
                object obj = ResourceManager.GetObject("calendar_and_user_icon_icons_com_70271", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cash_credit_currency_dollar_finance_money_payment_icon_123204_1_ {
            get {
                object obj = ResourceManager.GetObject("cash_credit_currency_dollar_finance_money_payment_icon_123204(1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon chart_charts_increase_arrow_business_icon_186855 {
            get {
                object obj = ResourceManager.GetObject("chart_charts_increase_arrow_business_icon_186855", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap chart_charts_increase_arrow_business_icon_1868551 {
            get {
                object obj = ResourceManager.GetObject("chart_charts_increase_arrow_business_icon_1868551", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap chart_person_filled_icon_200798 {
            get {
                object obj = ResourceManager.GetObject("chart_person_filled_icon_200798", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap check_payment_pay_icon_143297 {
            get {
                object obj = ResourceManager.GetObject("check_payment_pay_icon_143297", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap customer_man_avatar_person_people_thinking_about_shopping_shopping_ideas_icon_225089 {
            get {
                object obj = ResourceManager.GetObject("customer_man_avatar_person_people_thinking_about_shopping_shopping_ideas_icon_225" +
                        "089", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap customer_man_avatar_person_people_thinking_about_shopping_shopping_ideas_icon_225089_1_ {
            get {
                object obj = ResourceManager.GetObject("customer_man_avatar_person_people_thinking_about_shopping_shopping_ideas_icon_225" +
                        "089_1_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap customer_man_avatar_person_people_thinking_about_shopping_shopping_ideas_icon_225119 {
            get {
                object obj = ResourceManager.GetObject("customer_man_avatar_person_people_thinking_about_shopping_shopping_ideas_icon_225" +
                        "119", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon doc_success_icon_155483 {
            get {
                object obj = ResourceManager.GetObject("doc_success_icon_155483", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon document_documents_files_icon_152099 {
            get {
                object obj = ResourceManager.GetObject("document_documents_files_icon_152099", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap document_documents_files_icon_1520991 {
            get {
                object obj = ResourceManager.GetObject("document_documents_files_icon_1520991", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap document_person_filled_icon_199874 {
            get {
                object obj = ResourceManager.GetObject("document_person_filled_icon_199874", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ecommerce_home_market_mart_shop_shopping_store_icon_123207 {
            get {
                object obj = ResourceManager.GetObject("ecommerce_home_market_mart_shop_shopping_store_icon_123207", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ecommerce_home_market_mart_shop_shopping_store_icon_1232071 {
            get {
                object obj = ResourceManager.GetObject("ecommerce_home_market_mart_shop_shopping_store_icon_1232071", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Edit_File_icon_icons_com_55923 {
            get {
                object obj = ResourceManager.GetObject("Edit_File_icon_icons_com_55923", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Edit_User_icon_icons_com_55920 {
            get {
                object obj = ResourceManager.GetObject("Edit_User_icon_icons_com_55920", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap editdocument_105148 {
            get {
                object obj = ResourceManager.GetObject("editdocument_105148", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap editdocument_1051481 {
            get {
                object obj = ResourceManager.GetObject("editdocument_1051481", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fiatmoneycashhandvalueshowbill_95897 {
            get {
                object obj = ResourceManager.GetObject("fiatmoneycashhandvalueshowbill_95897", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fiatmoneycashhandvalueshowbill_958971 {
            get {
                object obj = ResourceManager.GetObject("fiatmoneycashhandvalueshowbill_958971", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon financial_report_calculator_chart_pie_icon_205131 {
            get {
                object obj = ResourceManager.GetObject("financial_report_calculator_chart_pie_icon_205131", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap financial_report_calculator_chart_pie_icon_2051311 {
            get {
                object obj = ResourceManager.GetObject("financial_report_calculator_chart_pie_icon_2051311", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hand_money_icon_232218 {
            get {
                object obj = ResourceManager.GetObject("hand_money_icon_232218", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap income_money_bag_investment_finance_revenue_profit_dollar_icon_232660 {
            get {
                object obj = ResourceManager.GetObject("income_money_bag_investment_finance_revenue_profit_dollar_icon_232660", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap income_money_bag_investment_finance_revenue_profit_dollar_icon_232660_1_ {
            get {
                object obj = ResourceManager.GetObject("income_money_bag_investment_finance_revenue_profit_dollar_icon_232660(1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap invoice_transaction_bill_receipt_investment_dollar_icon_188468 {
            get {
                object obj = ResourceManager.GetObject("invoice_transaction_bill_receipt_investment_dollar_icon_188468", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap invoice_transaction_bill_receipt_investment_dollar_icon_188468_1_ {
            get {
                object obj = ResourceManager.GetObject("invoice_transaction_bill_receipt_investment_dollar_icon_188468_1_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap list_statistics_graph_report_icon_220489 {
            get {
                object obj = ResourceManager.GetObject("list_statistics_graph_report_icon_220489", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap money_bank_check_payment_cheque_icon_192197 {
            get {
                object obj = ResourceManager.GetObject("money_bank_check_payment_cheque_icon_192197", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap money_bank_check_payment_cheque_icon_192197_1_ {
            get {
                object obj = ResourceManager.GetObject("money_bank_check_payment_cheque_icon_192197_1_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap money_cash_payment_earning_salary_income_wages_icon_210499 {
            get {
                object obj = ResourceManager.GetObject("money_cash_payment_earning_salary_income_wages_icon_210499", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap money_cash_payment_earning_salary_income_wages_icon_210499_1_ {
            get {
                object obj = ResourceManager.GetObject("money_cash_payment_earning_salary_income_wages_icon_210499_1_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap notepad_person_filled_icon_202046 {
            get {
                object obj = ResourceManager.GetObject("notepad_person_filled_icon_202046", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap notepad_person_filled_icon_202046_1_ {
            get {
                object obj = ResourceManager.GetObject("notepad_person_filled_icon_202046_1_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon office_business_strategy_success_task_icon_190997 {
            get {
                object obj = ResourceManager.GetObject("office_business_strategy_success_task_icon_190997", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap page_paper_file_document_clock_loading_history_icon_228123_1_ {
            get {
                object obj = ResourceManager.GetObject("page_paper_file_document_clock_loading_history_icon_228123(1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap page_paper_file_document_delete_recycle_bin_icon_228146 {
            get {
                object obj = ResourceManager.GetObject("page_paper_file_document_delete_recycle_bin_icon_228146", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap page_paper_file_document_icon_228144 {
            get {
                object obj = ResourceManager.GetObject("page_paper_file_document_icon_228144", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap page_paper_file_document_write_pencil_icon_228145 {
            get {
                object obj = ResourceManager.GetObject("page_paper_file_document_write_pencil_icon_228145", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pay_cash_bill_money_buy_icon_143287 {
            get {
                object obj = ResourceManager.GetObject("pay_cash_bill_money_buy_icon_143287", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pay_cash_bill_money_buy_icon_143287_1_ {
            get {
                object obj = ResourceManager.GetObject("pay_cash_bill_money_buy_icon_143287_1_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pay_payment_bill_dollar_cash_icon_143281 {
            get {
                object obj = ResourceManager.GetObject("pay_payment_bill_dollar_cash_icon_143281", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap payment_tax_invoice_document_calculator_icon_188684 {
            get {
                object obj = ResourceManager.GetObject("payment_tax_invoice_document_calculator_icon_188684", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap person_add_filled_icon_202016 {
            get {
                object obj = ResourceManager.GetObject("person_add_filled_icon_202016", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap person_add_filled_icon_202016__1_ {
            get {
                object obj = ResourceManager.GetObject("person_add_filled_icon_202016__1_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap person_available_filled_icon_200415 {
            get {
                object obj = ResourceManager.GetObject("person_available_filled_icon_200415", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap person_call_filled_icon_200413 {
            get {
                object obj = ResourceManager.GetObject("person_call_filled_icon_200413", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap person_delete_filled_icon_199757 {
            get {
                object obj = ResourceManager.GetObject("person_delete_filled_icon_199757", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap person_edit_filled_icon_200410 {
            get {
                object obj = ResourceManager.GetObject("person_edit_filled_icon_200410", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap person_note_filled_icon_199756 {
            get {
                object obj = ResourceManager.GetObject("person_note_filled_icon_199756", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap person_note_filled_icon_202006 {
            get {
                object obj = ResourceManager.GetObject("person_note_filled_icon_202006", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap person_note_filled_icon_202006_1_ {
            get {
                object obj = ResourceManager.GetObject("person_note_filled_icon_202006_1_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap person_prohibited_filled_icon_200402 {
            get {
                object obj = ResourceManager.GetObject("person_prohibited_filled_icon_200402", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap person_stalker_icon_icons_com_50076 {
            get {
                object obj = ResourceManager.GetObject("person_stalker_icon_icons_com_50076", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon pie_chart_with_a_circle_of_arrows_icon_icons_com_56765 {
            get {
                object obj = ResourceManager.GetObject("pie_chart_with_a_circle_of_arrows_icon_icons_com_56765", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pie_chart_with_a_circle_of_arrows_icon_icons_com_567651 {
            get {
                object obj = ResourceManager.GetObject("pie_chart_with_a_circle_of_arrows_icon_icons_com_567651", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap printer_with_print_and_paper_sheets_icon_icons_com_56231 {
            get {
                object obj = ResourceManager.GetObject("printer_with_print_and_paper_sheets_icon_icons_com_56231", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon question_icon_124050 {
            get {
                object obj = ResourceManager.GetObject("question_icon_124050", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap question_icon_1240501 {
            get {
                object obj = ResourceManager.GetObject("question_icon_1240501", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap seo_social_web_network_internet_176_icon_icons_com_61495 {
            get {
                object obj = ResourceManager.GetObject("seo_social_web_network_internet_176_icon_icons_com_61495", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon service_help_customer_question_communication_information_support_icon_261681 {
            get {
                object obj = ResourceManager.GetObject("service_help_customer_question_communication_information_support_icon_261681", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap service_help_customer_question_communication_information_support_icon_2616811 {
            get {
                object obj = ResourceManager.GetObject("service_help_customer_question_communication_information_support_icon_2616811", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon shop_place_marker_address_location_pin_map_ecommerce_icon_224950 {
            get {
                object obj = ResourceManager.GetObject("shop_place_marker_address_location_pin_map_ecommerce_icon_224950", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap shop_place_marker_address_location_pin_map_ecommerce_icon_2249501 {
            get {
                object obj = ResourceManager.GetObject("shop_place_marker_address_location_pin_map_ecommerce_icon_2249501", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap textandimagedocument_83677 {
            get {
                object obj = ResourceManager.GetObject("textandimagedocument_83677", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon thefreeforty_target_icon_icons_com_66342 {
            get {
                object obj = ResourceManager.GetObject("thefreeforty_target_icon_icons_com_66342", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon thefreeforty_target_icon_icons_com_66342__1_ {
            get {
                object obj = ResourceManager.GetObject("thefreeforty_target_icon_icons_com_66342__1_", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap transaction_cash_flow_dollar_finance_transfer_payment_icon_232617 {
            get {
                object obj = ResourceManager.GetObject("transaction_cash_flow_dollar_finance_transfer_payment_icon_232617", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap window_ad_person_filled_icon_200070 {
            get {
                object obj = ResourceManager.GetObject("window_ad_person_filled_icon_200070", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap window_ad_person_filled_icon_200070_1_ {
            get {
                object obj = ResourceManager.GetObject("window_ad_person_filled_icon_200070_1_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap workplace_workspace_desktop_workstation_icon_188678 {
            get {
                object obj = ResourceManager.GetObject("workplace_workspace_desktop_workstation_icon_188678", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
